[gcp_service_account]
type = "service_account"
project_id = "static-lead-464709-p1"
private_key_id = "887234a0c6061ad7dd8d10bd2a1b601110d94ae1"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCqLYuS2s0Z7hQq
Otr/2nu75tBPHzTpQImho/ovnWFXPk2+1uycMiAWx++ooIE2PmNf0oRyIeMfc0aZ
XQFa1BIksAGYaJeXlUeLF5pc/zDD1PvzJR2Z5bQSKmqTy+HOZXm1LxA8MHhDzD6H
sSxZyo/9aLq9Yp0zuGQiuO520DgR2RRWzJbqvJnzXpt+CMHdUmPVFZJbH8nnOPuv
tUqibCIgGsAVkSuCUbW3wvAJgitfklYK7dXcIEjhIo2dyw0ea8BFSY1t7zmJZATp
SYxyhcPYGwIJ4bsfZrS88byweaxw697aTk9Em4i58OtH9VCFvEPZQEBgFz6px23J
4M63ACWJAgMBAAECggEAKinVqoF+jp2frmTdrMWHoaMK2oerVt1QHFXh31k5bGG5
5n4eqoZ6z9oipV97FCL6ARxKB3Mg8EJh7A6Qjt37Ts6y3n2PjZWFX89txfvOK78B
25jHEEHKzzNmK484t6gJsxvhhGAn8/hPR9RcXjTjXxBLMDAWLeHSIY47OwHU2orM
C+0ULskOsW+M4QBdjooWvZUX2vtiadiSL7fCODGudGLLPKCHfMDHAo/nket2lpd3
eKVVwL5PvibM6rhnHUNXk1vtguX0GjQkqllXTEm0VwOu4rKzTC4vHLpxd0A+61rV
xYFtOgYmK4e8y9XrAwHuSHhHWfuvnP8fWjU4vhQGTwKBgQDiWs10iVpmUmhyP32/
MLTGTmFWqs1X26l/OPsUJEPa4n8ReWh+TD5JyzAeUA2Fc4Eqw4Fajm8QWFLfmae+
O7fQtJ1rcbiGzhBn+WOSQZSiCgmDX5FP98O9O4k4AdmIzNBqI22l9aOqajKbiB93
csffC+4Ny1sUX/P7WuCgB4ZvJwKBgQDAd0DGMurgkt7u0JZWXpRnUfAdAcn4D2ha
wmuzBWZAge0SbPWRxB+Ej5xdCxFUi5IQErKQIQzGKSaIjk5N9/C5W8kOtsvwWb9D
4hRRrrL9Cwr6JXHt4Vonqf801xXoimujwTF7YgoFFcgAoG0X5Q2NOkFOoeYmAUp3
ezvjjkyzzwKBgQCkEy/UZm+5tchx8CXlPZf8GvqhyONZ6Sb+yj3thrAM7Jsw/nFJ
A1kvQnKZtmtmragWaGrOSmqlTXCdFhMqaL1AMnvdUyxvwtTPmU2cyZ7EqkPlD5QU
hENFWu+HQof9ioEUPqQPZXQCZkJSzSQKAJBy1IH1S8+0gC0pqOEj/vBqhwKBgQCz
APbcn9S148O2B4gbckHCSoHw6I4IyYO8DeEPEnGEg5KTtYU7+lV5+/toyfdnU5wY
mNs8k5CG6RTuorQPbg+UxdocdkT9GOt73lQZmErecBvYhWUN4q7v/vreEUFOExeD
qRY1c/xvuE9YzdxJAf71n/3HfWpJZJ/2ukX8IYgTHwKBgBMyyVw6KjOjvLFHbdR6
ShdxVDfsGtHQeOQbHqzf51b5v9UgFJkHrYzX1gUvKbAWPT+86YvJV23T6oGfMIR8
Gw3eBGGHh7MmEKdX8ZD8ktDh9yxio25XDWFgfUvGWL2QcpeBEhjHJySJKnhMUpJ2
go/4UFzbKJ6aWzZVV9BVsq4i
-----END PRIVATE KEY-----"""
client_email = "marketintelgas@static-lead-464709-p1.iam.gserviceaccount.com"
client_id = "117609164786586381083"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/marketintelgas%40static-lead-464709-p1.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
